### ISSUE TITLE
Eugen's Pull Request fehlt!!! oder wurde noch nicht gemergt!!!

### ISSUE THREAD

**Issue by IB-2015** [erikmartens/aps_snake#7]
Ich kann nicht ohne Eugen's merge anfangen, da wir da noch was gemacht haben, was ich brauch.

**Comment by erikmartens** [comment]
Ich habe alles gemerged was offen war. Wenn du in den Pullrequest Tab gehst, siehst du, dass nichts offen ist. Wenn du dort auf "closed" gehst, siehst alle bereits gemergten PRs. Hat Eugen den Request überhaupt schon aufgemacht?

**Comment by IB-2015** [comment]
er hatte keinen pull request gemacht. wir haben es gerade geklärt. is alles ok

**Comment by erikmartens** [comment]
👌
